## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999

branches:
  only:
    - master
    - /release-.*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

# uncomment the following lines to override the default test script
script:
 - julia -e 'using Pkg; Pkg.activate(pwd()); pkg"instantiate"'
 - julia -e 'using Pkg; Pkg.activate(pwd()); pkg"add https://github.com/jagot/PseudoPotentials.jl.git"'
 - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/JuliaAtoms/AtomicLevels.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/JuliaAtoms/EnergyExpressions.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/JuliaAtoms/AngularMomentumAlgebra.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add LazyArrays"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/JuliaApproximation/ContinuumArrays.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/jagot/FiniteDifferencesQuasi.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/jagot/FEDVRQuasi.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/jagot/IterativeFactorizations.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/jagot/CoulombIntegrals.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/jagot/SolverTraces.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/JuliaAtoms/SCF.jl.git"'
        - julia --project=docs/ -e 'using Pkg; pkg"add https://github.com/JuliaAtoms/AtomicPotentials.jl.git"'
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()));'
        - julia --project=docs/ docs/make.jl
      after_success: skip
